name: Currency Tracker

on:
  schedule:
    - cron: "0 */3 * * *"  # Каждые 3 часа
  workflow_dispatch:  # Ручной запуск

jobs:
  update-currencies:
    runs-on: ubuntu-latest
    steps:

      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content to github runner
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: pip install requests sqlite3 
      - name: Run script
        run: python src/main.py
      - name: Commit changes
        run: |
            git config --global user.email "actions@github.com"
            git config --global user.name "GitHub Actions"
            git add -A
            git commit --allow-empty -m "Auto-update currency data" || echo "No changes to commit"
      - name: push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main